services:
    recherche.service:
        class: GlobalBundle\Service\Recherche
        arguments: ["@session", "@request_stack"]

    fonctions.twig.service:
        class: GlobalBundle\Service\Twig\GetCurrentMenu
        arguments: ["@request_stack"]
        tags:
          -  { name: twig.extension }

    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    tool.service:
        class: GlobalBundle\Service\Tool

    upload.service:
        class: GlobalBundle\Service\Upload

    agenda.service:
        class: GlobalBundle\Service\Agenda