<?php

namespace PageBundle\Repository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllMenuAdmin($parent = null, $admin)
    {

        /* Requéte */
        $qb = $this->createQueryBuilder('m');

        if(is_null($parent)){
            $qb->andWhere('m.parent = 0');
        }else{
            $qb->andWhere('m.parent = :parent')
                ->setParameter('parent', $parent);
        }

        if(!$admin){
            $qb->andWhere('m.isActive = 1');
        }

        $qb->orderBy('m.poid', 'ASC');

        return $query = $qb->getQuery()->getResult();

    }

}
