referencement:
    resource: "@ReferencementBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

global:
    resource: "@GlobalBundle/Resources/config/routing.yml"
    prefix:   /

page:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /