<?php

namespace UserBundle\Repository;

/**
 * ReinitialisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReinitialisationRepository extends \Doctrine\ORM\EntityRepository
{
}
