<?php

namespace ReferencementBundle\Repository;

/**
 * ReferencementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferencementRepository extends \Doctrine\ORM\EntityRepository
{
}
