login:
    path: /connexion
    defaults: { _controller: UserBundle:User:Login }

logout:
    path: /logout

register:
    path: /inscription
    defaults: { _controller: UserBundle:User:Register }

#Newsletter
client_newsletter_ajout:
    path: /newsletter-inscription
    defaults: { _controller: UserBundle:User:ClientNewsletterAjouter }

admin_newsletter_export:
    path: /newsletter-export
    defaults: { _controller: UserBundle:User:AdminNewsletterExport }

#Réinitialisation de mot de passe
reinitialisation:
    path: /reinitialisation
    defaults: { _controller: UserBundle:User:Reinitialisation }

reinitialisation_password:
    path: /reinitialisation/mot-de-passe/{token}
    defaults: { _controller: UserBundle:User:ReinitialisationPassword }
    requirements:
        token: ([a-z-0-9]*)

#Gestion compte back office
admin_user_compte_modifier:
    path: /admin/compte/modifier
    defaults: { _controller: UserBundle:User:AdminCompteModifier }

admin_user_compte_password:
    path: /admin/compte/password
    defaults: { _controller: UserBundle:User:AdminComptePassword }

#Gestion compte front office
compte_user_manager:
    path: /compte
    defaults: {_controller: UserBundle:User:ClientCompte}

#Gestion back office
admin_user_manager:
    path: /admin/user/manager
    defaults: { _controller: UserBundle:User:AdminManager }

admin_user_historique:
    path: /admin/user/historique
    defaults: { _controller: UserBundle:User:AdminHistorique }

admin_user_ajouter:
    path: /admin/user/ajouter
    defaults: { _controller: UserBundle:User:AdminAjouter }

admin_user_publier:
    path: /admin/user/publier/{id}
    defaults: { _controller: UserBundle:User:AdminPublier }
    requirements:
        id: \d+

admin_user_modifier:
    path: /admin/user/modifier/{id}
    defaults: { _controller: UserBundle:User:AdminModifier }
    requirements:
        id: \d+

admin_user_modifier_password:
    path: /admin/user/password/{id}
    defaults: { _controller: UserBundle:User:AdminModifierPassword }
    requirements:
        id: \d+

admin_user_supprimer_avatar:
    path: /admin/user/supprimer-avatar/{id}
    defaults: { _controller: UserBundle:User:AdminSupprimerAvatar }
    requirements:
        id: \d+
